# Generated by Django 4.2.21 on 2025-06-03 21:43

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at'], 'verbose_name': 'CV Profili', 'verbose_name_plural': 'CV Profilleri'},
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, help_text='İkamet adresiniz (Opsiyonel)', max_length=300, null=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='profile',
            name='certifications',
            field=models.TextField(blank=True, help_text='Sahip olduğunuz profesyonel sertifikalar (Opsiyonel)', max_length=1000, null=True, verbose_name='Sertifikalar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='current_position',
            field=models.CharField(blank=True, help_text='Şu anki çalıştığınız pozisyon (Opsiyonel)', max_length=100, null=True, verbose_name='Mevcut Pozisyon'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_years',
            field=models.IntegerField(blank=True, help_text='Toplam çalışma deneyiminiz yıl olarak', null=True, verbose_name='Toplam Deneyim (Yıl)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profil linkiniz (Opsiyonel)', null=True, verbose_name='GitHub Profili'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='4.0 üzerinden not ortalamanız (Opsiyonel)', max_digits=4, null=True, verbose_name='GPA/Not Ortalaması'),
        ),
        migrations.AddField(
            model_name='profile',
            name='graduation_year',
            field=models.IntegerField(blank=True, help_text='Üniversiteden mezun olduğunuz yıl', null=True, verbose_name='Mezuniyet Yılı'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.TextField(blank=True, help_text='İlgi alanlarınız ve hobileriniz (Opsiyonel)', max_length=500, null=True, verbose_name='Hobiler'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True, help_text="CV'nin aktif olup olmadığı", verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.TextField(blank=True, help_text='Bildiğiniz dilleri ve seviyelerini yazın (Opsiyonel)', max_length=500, null=True, verbose_name='Dil Becerileri'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profil linkiniz (Opsiyonel)', null=True, verbose_name='LinkedIn Profili'),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Kişisel website/portfolio linkiniz (Opsiyonel)', null=True, verbose_name='Portfolio Website'),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.TextField(blank=True, help_text='Katıldığınız önemli projeler (Opsiyonel)', max_length=1500, null=True, verbose_name='Projeler'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(help_text='Örnek: Lisans, Yüksek Lisans, Doktora', max_length=100, verbose_name='Eğitim Seviyesi'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(help_text='Geçerli bir e-posta adresi giriniz', max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='E-posta Adresi'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(help_text='Tam adınızı giriniz', max_length=100, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(help_text='Örnek: +905551234567', max_length=17, validators=[django.core.validators.RegexValidator(message="Telefon numarası '+999999999' formatında olmalıdır. 15 haneden fazla olamaz.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='previous_work',
            field=models.TextField(help_text='Önceki iş deneyimlerinizi kronolojik sırayla yazın', max_length=2000, verbose_name='İş Deneyimi'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(help_text='Mezun olduğunuz lise', max_length=100, verbose_name='Lise'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(help_text='Teknik ve kişisel becerilerinizi listeleyin', max_length=2000, verbose_name='Beceriler'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.TextField(help_text='Kendinizi ve kariyerinizi kısaca tanıtın', max_length=2000, verbose_name='Profesyonel Özet'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(help_text='Mezun olduğunuz üniversite ve bölüm', max_length=100, verbose_name='Üniversite'),
        ),
    ]
